# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.baskets_api import BasketsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBasketsApi(unittest.TestCase):
    """BasketsApi unit test stubs"""

    def setUp(self):
        self.api = BasketsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_one_basket_api_v1_baskets_basket_id_delete(self):
        """Test case for delete_one_basket_api_v1_baskets_basket_id_delete

        Delete One Basket  # noqa: E501
        """
        pass

    def test_delete_user_basket_api_v1_baskets_users_user_id_delete(self):
        """Test case for delete_user_basket_api_v1_baskets_users_user_id_delete

        Delete User Basket  # noqa: E501
        """
        pass

    def test_get_basket_api_v1_baskets_get(self):
        """Test case for get_basket_api_v1_baskets_get

        Get Basket  # noqa: E501
        """
        pass

    def test_get_count_basket_api_v1_baskets_all_count_get(self):
        """Test case for get_count_basket_api_v1_baskets_all_count_get

        Get Count Basket  # noqa: E501
        """
        pass

    def test_get_list_id_basket_api_v1_baskets_all_list_id_get(self):
        """Test case for get_list_id_basket_api_v1_baskets_all_list_id_get

        Get List Id Basket  # noqa: E501
        """
        pass

    def test_get_one_basket_api_v1_baskets_basket_id_get(self):
        """Test case for get_one_basket_api_v1_baskets_basket_id_get

        Get One Basket  # noqa: E501
        """
        pass

    def test_insert_api_v1_baskets_post(self):
        """Test case for insert_api_v1_baskets_post

        Insert  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
