# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.items_api import ItemsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestItemsApi(unittest.TestCase):
    """ItemsApi unit test stubs"""

    def setUp(self):
        self.api = ItemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_brands_and_counts_api_v1_items_category_brands_counts_get(self):
        """Test case for get_brands_and_counts_api_v1_items_category_brands_counts_get

        Get Brands And Counts  # noqa: E501
        """
        pass

    def test_get_codes_items_api_v1_items_codes_get(self):
        """Test case for get_codes_items_api_v1_items_codes_get

        Get Codes Items  # noqa: E501
        """
        pass

    def test_get_item_api_v1_items_code_token_one_get(self):
        """Test case for get_item_api_v1_items_code_token_one_get

        Get Item  # noqa: E501
        """
        pass

    def test_get_item_new_api_v1_items_code_token_one_new_get(self):
        """Test case for get_item_new_api_v1_items_code_token_one_new_get

        Get Item New  # noqa: E501
        """
        pass

    def test_get_item_selectinload_size_api_v1_items_code_token_load_size_get(self):
        """Test case for get_item_selectinload_size_api_v1_items_code_token_load_size_get

        Get Item Selectinload Size  # noqa: E501
        """
        pass

    def test_get_item_selectinload_size_category_api_v1_items_code_token_load_size_category_get(self):
        """Test case for get_item_selectinload_size_category_api_v1_items_code_token_load_size_category_get

        Get Item Selectinload Size Category  # noqa: E501
        """
        pass

    def test_get_item_selectinload_size_centimeter_category_api_v1_items_code_token_load_size_centimeter_category_get(self):
        """Test case for get_item_selectinload_size_centimeter_category_api_v1_items_code_token_load_size_centimeter_category_get

        Get Item Selectinload Size Centimeter Category  # noqa: E501
        """
        pass

    def test_get_items_action_api_v1_items_token_all_get(self):
        """Test case for get_items_action_api_v1_items_token_all_get

        Get Items Action  # noqa: E501
        """
        pass

    def test_get_items_action_new_codes_api_v1_items_token_all_new_codes_get(self):
        """Test case for get_items_action_new_codes_api_v1_items_token_all_new_codes_get

        Get Items Action New Codes  # noqa: E501
        """
        pass

    def test_get_items_api_v1_items_category_brand_token_get(self):
        """Test case for get_items_api_v1_items_category_brand_token_get

        Get Items  # noqa: E501
        """
        pass

    def test_get_items_codes_api_v1_items_category_brand_codes_get(self):
        """Test case for get_items_codes_api_v1_items_category_brand_codes_get

        Get Items Codes  # noqa: E501
        """
        pass

    def test_get_models_and_counts_api_v1_items_category_brand_models_counts_get(self):
        """Test case for get_models_and_counts_api_v1_items_category_brand_models_counts_get

        Get Models And Counts  # noqa: E501
        """
        pass

    def test_get_models_api_v1_items_category_brand_models_get(self):
        """Test case for get_models_api_v1_items_category_brand_models_get

        Get Models  # noqa: E501
        """
        pass

    def test_insert_or_update_api_v1_items_merge_post(self):
        """Test case for insert_or_update_api_v1_items_merge_post

        Insert Or Update  # noqa: E501
        """
        pass

    def test_update_active_api_v1_items_active_put(self):
        """Test case for update_active_api_v1_items_active_put

        Update Active  # noqa: E501
        """
        pass

    def test_update_photo_by_code_api_v1_items_photo_code_file_id_photo_put(self):
        """Test case for update_photo_by_code_api_v1_items_photo_code_file_id_photo_put

        Update Photo By Code  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
