# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.categories_api import CategoriesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCategoriesApi(unittest.TestCase):
    """CategoriesApi unit test stubs"""

    def setUp(self):
        self.api = CategoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_categories_name_api_v1_categories_get(self):
        """Test case for get_categories_name_api_v1_categories_get

        Get Categories Name  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
