# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.purchases_api import PurchasesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPurchasesApi(unittest.TestCase):
    """PurchasesApi unit test stubs"""

    def setUp(self):
        self.api = PurchasesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_purchase_api_v1_purchases_purchase_id_delete(self):
        """Test case for delete_purchase_api_v1_purchases_purchase_id_delete

        Delete Purchase  # noqa: E501
        """
        pass

    def test_get_all_api_v1_purchases_get(self):
        """Test case for get_all_api_v1_purchases_get

        Get All  # noqa: E501
        """
        pass

    def test_get_count_api_v1_purchases_token_status_count_get(self):
        """Test case for get_count_api_v1_purchases_token_status_count_get

        Get Count  # noqa: E501
        """
        pass

    def test_get_purchase_by_id_api_v1_purchases_purchase_id_get(self):
        """Test case for get_purchase_by_id_api_v1_purchases_purchase_id_get

        Get Purchase By Id  # noqa: E501
        """
        pass

    def test_update_only_api_v1_purchases_put(self):
        """Test case for update_only_api_v1_purchases_put

        Update Only  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
