# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.orders_api import OrdersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self):
        self.api = OrdersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_order_api_v1_orders_order_id_delete(self):
        """Test case for delete_order_api_v1_orders_order_id_delete

        Delete Order  # noqa: E501
        """
        pass

    def test_get_active_orders_api_v1_orders_get(self):
        """Test case for get_active_orders_api_v1_orders_get

        Get Active Orders  # noqa: E501
        """
        pass

    def test_get_count_orders_api_v1_orders_count_get(self):
        """Test case for get_count_orders_api_v1_orders_count_get

        Get Count Orders  # noqa: E501
        """
        pass

    def test_get_count_orders_by_user_id_api_v1_orders_users_user_id_count_get(self):
        """Test case for get_count_orders_by_user_id_api_v1_orders_users_user_id_count_get

        Get Count Orders By User Id  # noqa: E501
        """
        pass

    def test_get_order_by_id_api_v1_orders_order_id_get(self):
        """Test case for get_order_by_id_api_v1_orders_order_id_get

        Get Order By Id  # noqa: E501
        """
        pass

    def test_get_user_orders_api_v1_orders_users_user_id_get(self):
        """Test case for get_user_orders_api_v1_orders_users_user_id_get

        Get User Orders  # noqa: E501
        """
        pass

    def test_insert_order_api_v1_orders_post(self):
        """Test case for insert_order_api_v1_orders_post

        Insert Order  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
