# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.bots_api import BotsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBotsApi(unittest.TestCase):
    """BotsApi unit test stubs"""

    def setUp(self):
        self.api = BotsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_bot_api_v1_bots_token_get(self):
        """Test case for get_bot_api_v1_bots_token_get

        Get Bot  # noqa: E501
        """
        pass

    def test_get_bots_api_v1_bots_get(self):
        """Test case for get_bots_api_v1_bots_get

        Get Bots  # noqa: E501
        """
        pass

    def test_get_tokens_multibot_api_v1_bots_multibot_tokens_get(self):
        """Test case for get_tokens_multibot_api_v1_bots_multibot_tokens_get

        Get Tokens Multibot  # noqa: E501
        """
        pass

    def test_insert_or_nothing_api_v1_bots_post(self):
        """Test case for insert_or_nothing_api_v1_bots_post

        Insert Or Nothing  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
