# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.messages_tg_api import MessagesTgApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMessagesTgApi(unittest.TestCase):
    """MessagesTgApi unit test stubs"""

    def setUp(self):
        self.api = MessagesTgApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_api_v1_messages_tg_name_get(self):
        """Test case for get_api_v1_messages_tg_name_get

        Get  # noqa: E501
        """
        pass

    def test_insert_or_update_api_v1_messages_tg_post(self):
        """Test case for insert_or_update_api_v1_messages_tg_post

        Insert Or Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
