# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_item_new import GetItemNew  # noqa: E501
from swagger_client.rest import ApiException


class TestGetItemNew(unittest.TestCase):
    """GetItemNew unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetItemNew(self):
        """Test GetItemNew"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_item_new.GetItemNew()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
