# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.users_bots_api import UsersBotsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsersBotsApi(unittest.TestCase):
    """UsersBotsApi unit test stubs"""

    def setUp(self):
        self.api = UsersBotsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_ids_users_api_v1_users_bots_ids_get(self):
        """Test case for get_all_ids_users_api_v1_users_bots_ids_get

        Get All Ids Users  # noqa: E501
        """
        pass

    def test_get_count_api_v1_users_bots_count_get(self):
        """Test case for get_count_api_v1_users_bots_count_get

        Get Count  # noqa: E501
        """
        pass

    def test_get_only_user_bot_api_v1_users_bots_user_id_only_get(self):
        """Test case for get_only_user_bot_api_v1_users_bots_user_id_only_get

        Get Only User Bot  # noqa: E501
        """
        pass

    def test_get_user_bot_api_v1_users_bots_user_id_get(self):
        """Test case for get_user_bot_api_v1_users_bots_user_id_get

        Get User Bot  # noqa: E501
        """
        pass

    def test_get_user_bot_start_api_v1_users_bots_user_id_start_get(self):
        """Test case for get_user_bot_start_api_v1_users_bots_user_id_start_get

        Get User Bot Start  # noqa: E501
        """
        pass

    def test_get_user_client_bot_api_v1_users_bots_user_id_client_get(self):
        """Test case for get_user_client_bot_api_v1_users_bots_user_id_client_get

        Get User Client Bot  # noqa: E501
        """
        pass

    def test_update_last_mess_api_v1_users_bots_mess_put(self):
        """Test case for update_last_mess_api_v1_users_bots_mess_put

        Update Last Mess  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
