# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.users_api import UsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_ids_users_api_v1_users_ids_get(self):
        """Test case for get_all_ids_users_api_v1_users_ids_get

        Get All Ids Users  # noqa: E501
        """
        pass

    def test_get_all_users_api_v1_users_get(self):
        """Test case for get_all_users_api_v1_users_get

        Get All Users  # noqa: E501
        """
        pass

    def test_get_user_api_v1_users_user_id_get(self):
        """Test case for get_user_api_v1_users_user_id_get

        Get User  # noqa: E501
        """
        pass

    def test_get_user_client_api_v1_users_clients_user_id_get(self):
        """Test case for get_user_client_api_v1_users_clients_user_id_get

        Get User Client  # noqa: E501
        """
        pass

    def test_get_user_codes_api_v1_users_user_id_codes_get(self):
        """Test case for get_user_codes_api_v1_users_user_id_codes_get

        Get User Codes  # noqa: E501
        """
        pass

    def test_update_last_mess_api_v1_users_user_id_mess_put(self):
        """Test case for update_last_mess_api_v1_users_user_id_mess_put

        Update Last Mess  # noqa: E501
        """
        pass

    def test_update_user_items_api_v1_users_user_id_items_put(self):
        """Test case for update_user_items_api_v1_users_user_id_items_put

        Update User Items  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
