# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sizes_api import SizesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSizesApi(unittest.TestCase):
    """SizesApi unit test stubs"""

    def setUp(self):
        self.api = SizesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_size_by_id_api_v1_sizes_size_id_get(self):
        """Test case for get_size_by_id_api_v1_sizes_size_id_get

        Get Size By Id  # noqa: E501
        """
        pass

    def test_get_sizes_api_v1_sizes_get(self):
        """Test case for get_sizes_api_v1_sizes_get

        Get Sizes  # noqa: E501
        """
        pass

    def test_insert_or_nothing_api_v1_sizes_post(self):
        """Test case for insert_or_nothing_api_v1_sizes_post

        Insert Or Nothing  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
