# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.waybills_api import WaybillsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWaybillsApi(unittest.TestCase):
    """WaybillsApi unit test stubs"""

    def setUp(self):
        self.api = WaybillsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_update_api_v1_waybills_put(self):
        """Test case for update_api_v1_waybills_put

        Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
