# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.schedulers_api import SchedulersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSchedulersApi(unittest.TestCase):
    """SchedulersApi unit test stubs"""

    def setUp(self):
        self.api = SchedulersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_api_v1_schedulers_scheduler_id_delete(self):
        """Test case for delete_api_v1_schedulers_scheduler_id_delete

        Delete  # noqa: E501
        """
        pass

    def test_get_api_v1_schedulers_get(self):
        """Test case for get_api_v1_schedulers_get

        Get  # noqa: E501
        """
        pass

    def test_insert_api_v1_schedulers_post(self):
        """Test case for insert_api_v1_schedulers_post

        Insert  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
