# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BarcodeInsert(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'delivery_cdek_id': 'int',
        'barcode_id': 'str',
        'tg_file_id': 'str'
    }

    attribute_map = {
        'delivery_cdek_id': 'delivery_cdek_id',
        'barcode_id': 'barcode_id',
        'tg_file_id': 'tg_file_id'
    }

    def __init__(self, delivery_cdek_id=None, barcode_id=None, tg_file_id=None):  # noqa: E501
        """BarcodeInsert - a model defined in Swagger"""  # noqa: E501
        self._delivery_cdek_id = None
        self._barcode_id = None
        self._tg_file_id = None
        self.discriminator = None
        self.delivery_cdek_id = delivery_cdek_id
        self.barcode_id = barcode_id
        self.tg_file_id = tg_file_id

    @property
    def delivery_cdek_id(self):
        """Gets the delivery_cdek_id of this BarcodeInsert.  # noqa: E501


        :return: The delivery_cdek_id of this BarcodeInsert.  # noqa: E501
        :rtype: int
        """
        return self._delivery_cdek_id

    @delivery_cdek_id.setter
    def delivery_cdek_id(self, delivery_cdek_id):
        """Sets the delivery_cdek_id of this BarcodeInsert.


        :param delivery_cdek_id: The delivery_cdek_id of this BarcodeInsert.  # noqa: E501
        :type: int
        """
        if delivery_cdek_id is None:
            raise ValueError("Invalid value for `delivery_cdek_id`, must not be `None`")  # noqa: E501

        self._delivery_cdek_id = delivery_cdek_id

    @property
    def barcode_id(self):
        """Gets the barcode_id of this BarcodeInsert.  # noqa: E501


        :return: The barcode_id of this BarcodeInsert.  # noqa: E501
        :rtype: str
        """
        return self._barcode_id

    @barcode_id.setter
    def barcode_id(self, barcode_id):
        """Sets the barcode_id of this BarcodeInsert.


        :param barcode_id: The barcode_id of this BarcodeInsert.  # noqa: E501
        :type: str
        """
        if barcode_id is None:
            raise ValueError("Invalid value for `barcode_id`, must not be `None`")  # noqa: E501

        self._barcode_id = barcode_id

    @property
    def tg_file_id(self):
        """Gets the tg_file_id of this BarcodeInsert.  # noqa: E501


        :return: The tg_file_id of this BarcodeInsert.  # noqa: E501
        :rtype: str
        """
        return self._tg_file_id

    @tg_file_id.setter
    def tg_file_id(self, tg_file_id):
        """Sets the tg_file_id of this BarcodeInsert.


        :param tg_file_id: The tg_file_id of this BarcodeInsert.  # noqa: E501
        :type: str
        """
        if tg_file_id is None:
            raise ValueError("Invalid value for `tg_file_id`, must not be `None`")  # noqa: E501

        self._tg_file_id = tg_file_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BarcodeInsert, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BarcodeInsert):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
