# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetUser(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'users_bots_id': 'int',
        'user_id': 'int',
        'first_name': 'str',
        'last_mess': 'int',
        'new_user': 'bool'
    }

    attribute_map = {
        'users_bots_id': 'users_bots_id',
        'user_id': 'user_id',
        'first_name': 'first_name',
        'last_mess': 'last_mess',
        'new_user': 'new_user'
    }

    def __init__(self, users_bots_id=None, user_id=None, first_name=None, last_mess=None, new_user=False):  # noqa: E501
        """GetUser - a model defined in Swagger"""  # noqa: E501
        self._users_bots_id = None
        self._user_id = None
        self._first_name = None
        self._last_mess = None
        self._new_user = None
        self.discriminator = None
        if users_bots_id is not None:
            self.users_bots_id = users_bots_id
        self.user_id = user_id
        self.first_name = first_name
        if last_mess is not None:
            self.last_mess = last_mess
        if new_user is not None:
            self.new_user = new_user

    @property
    def users_bots_id(self):
        """Gets the users_bots_id of this GetUser.  # noqa: E501


        :return: The users_bots_id of this GetUser.  # noqa: E501
        :rtype: int
        """
        return self._users_bots_id

    @users_bots_id.setter
    def users_bots_id(self, users_bots_id):
        """Sets the users_bots_id of this GetUser.


        :param users_bots_id: The users_bots_id of this GetUser.  # noqa: E501
        :type: int
        """

        self._users_bots_id = users_bots_id

    @property
    def user_id(self):
        """Gets the user_id of this GetUser.  # noqa: E501


        :return: The user_id of this GetUser.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this GetUser.


        :param user_id: The user_id of this GetUser.  # noqa: E501
        :type: int
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def first_name(self):
        """Gets the first_name of this GetUser.  # noqa: E501


        :return: The first_name of this GetUser.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this GetUser.


        :param first_name: The first_name of this GetUser.  # noqa: E501
        :type: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_mess(self):
        """Gets the last_mess of this GetUser.  # noqa: E501


        :return: The last_mess of this GetUser.  # noqa: E501
        :rtype: int
        """
        return self._last_mess

    @last_mess.setter
    def last_mess(self, last_mess):
        """Sets the last_mess of this GetUser.


        :param last_mess: The last_mess of this GetUser.  # noqa: E501
        :type: int
        """

        self._last_mess = last_mess

    @property
    def new_user(self):
        """Gets the new_user of this GetUser.  # noqa: E501


        :return: The new_user of this GetUser.  # noqa: E501
        :rtype: bool
        """
        return self._new_user

    @new_user.setter
    def new_user(self, new_user):
        """Sets the new_user of this GetUser.


        :param new_user: The new_user of this GetUser.  # noqa: E501
        :type: bool
        """

        self._new_user = new_user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetUser, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetUser):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
