# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetScheduler(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'user_id': 'int',
        'video_id': 'str',
        'text': 'str',
        'trigger_datetime': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'user_id': 'user_id',
        'video_id': 'video_id',
        'text': 'text',
        'trigger_datetime': 'trigger_datetime'
    }

    def __init__(self, id=None, user_id=None, video_id=None, text=None, trigger_datetime=None):  # noqa: E501
        """GetScheduler - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._user_id = None
        self._video_id = None
        self._text = None
        self._trigger_datetime = None
        self.discriminator = None
        self.id = id
        self.user_id = user_id
        self.video_id = video_id
        self.text = text
        self.trigger_datetime = trigger_datetime

    @property
    def id(self):
        """Gets the id of this GetScheduler.  # noqa: E501


        :return: The id of this GetScheduler.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GetScheduler.


        :param id: The id of this GetScheduler.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def user_id(self):
        """Gets the user_id of this GetScheduler.  # noqa: E501


        :return: The user_id of this GetScheduler.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this GetScheduler.


        :param user_id: The user_id of this GetScheduler.  # noqa: E501
        :type: int
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def video_id(self):
        """Gets the video_id of this GetScheduler.  # noqa: E501


        :return: The video_id of this GetScheduler.  # noqa: E501
        :rtype: str
        """
        return self._video_id

    @video_id.setter
    def video_id(self, video_id):
        """Sets the video_id of this GetScheduler.


        :param video_id: The video_id of this GetScheduler.  # noqa: E501
        :type: str
        """
        if video_id is None:
            raise ValueError("Invalid value for `video_id`, must not be `None`")  # noqa: E501

        self._video_id = video_id

    @property
    def text(self):
        """Gets the text of this GetScheduler.  # noqa: E501


        :return: The text of this GetScheduler.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this GetScheduler.


        :param text: The text of this GetScheduler.  # noqa: E501
        :type: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def trigger_datetime(self):
        """Gets the trigger_datetime of this GetScheduler.  # noqa: E501


        :return: The trigger_datetime of this GetScheduler.  # noqa: E501
        :rtype: datetime
        """
        return self._trigger_datetime

    @trigger_datetime.setter
    def trigger_datetime(self, trigger_datetime):
        """Sets the trigger_datetime of this GetScheduler.


        :param trigger_datetime: The trigger_datetime of this GetScheduler.  # noqa: E501
        :type: datetime
        """
        if trigger_datetime is None:
            raise ValueError("Invalid value for `trigger_datetime`, must not be `None`")  # noqa: E501

        self._trigger_datetime = trigger_datetime

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetScheduler, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetScheduler):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
