# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InsertOrderTemporally(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created': 'datetime',
        'user_bot_id': 'int',
        'buyer': 'str',
        'delivery': 'str',
        'address': 'str',
        'phone': 'str',
        'checking': 'bool',
        'payment_receipt': 'str',
        'comment': 'str',
        'info_delivery': 'str',
        'partner': 'bool'
    }

    attribute_map = {
        'created': 'created',
        'user_bot_id': 'user_bot_id',
        'buyer': 'buyer',
        'delivery': 'delivery',
        'address': 'address',
        'phone': 'phone',
        'checking': 'checking',
        'payment_receipt': 'payment_receipt',
        'comment': 'comment',
        'info_delivery': 'info_delivery',
        'partner': 'partner'
    }

    def __init__(self, created=None, user_bot_id=None, buyer=None, delivery=None, address=None, phone=None, checking=None, payment_receipt=None, comment=None, info_delivery=None, partner=None):  # noqa: E501
        """InsertOrderTemporally - a model defined in Swagger"""  # noqa: E501
        self._created = None
        self._user_bot_id = None
        self._buyer = None
        self._delivery = None
        self._address = None
        self._phone = None
        self._checking = None
        self._payment_receipt = None
        self._comment = None
        self._info_delivery = None
        self._partner = None
        self.discriminator = None
        self.created = created
        self.user_bot_id = user_bot_id
        self.buyer = buyer
        if delivery is not None:
            self.delivery = delivery
        if address is not None:
            self.address = address
        if phone is not None:
            self.phone = phone
        self.checking = checking
        if payment_receipt is not None:
            self.payment_receipt = payment_receipt
        if comment is not None:
            self.comment = comment
        if info_delivery is not None:
            self.info_delivery = info_delivery
        if partner is not None:
            self.partner = partner

    @property
    def created(self):
        """Gets the created of this InsertOrderTemporally.  # noqa: E501


        :return: The created of this InsertOrderTemporally.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this InsertOrderTemporally.


        :param created: The created of this InsertOrderTemporally.  # noqa: E501
        :type: datetime
        """
        if created is None:
            raise ValueError("Invalid value for `created`, must not be `None`")  # noqa: E501

        self._created = created

    @property
    def user_bot_id(self):
        """Gets the user_bot_id of this InsertOrderTemporally.  # noqa: E501


        :return: The user_bot_id of this InsertOrderTemporally.  # noqa: E501
        :rtype: int
        """
        return self._user_bot_id

    @user_bot_id.setter
    def user_bot_id(self, user_bot_id):
        """Sets the user_bot_id of this InsertOrderTemporally.


        :param user_bot_id: The user_bot_id of this InsertOrderTemporally.  # noqa: E501
        :type: int
        """
        if user_bot_id is None:
            raise ValueError("Invalid value for `user_bot_id`, must not be `None`")  # noqa: E501

        self._user_bot_id = user_bot_id

    @property
    def buyer(self):
        """Gets the buyer of this InsertOrderTemporally.  # noqa: E501


        :return: The buyer of this InsertOrderTemporally.  # noqa: E501
        :rtype: str
        """
        return self._buyer

    @buyer.setter
    def buyer(self, buyer):
        """Sets the buyer of this InsertOrderTemporally.


        :param buyer: The buyer of this InsertOrderTemporally.  # noqa: E501
        :type: str
        """
        if buyer is None:
            raise ValueError("Invalid value for `buyer`, must not be `None`")  # noqa: E501

        self._buyer = buyer

    @property
    def delivery(self):
        """Gets the delivery of this InsertOrderTemporally.  # noqa: E501


        :return: The delivery of this InsertOrderTemporally.  # noqa: E501
        :rtype: str
        """
        return self._delivery

    @delivery.setter
    def delivery(self, delivery):
        """Sets the delivery of this InsertOrderTemporally.


        :param delivery: The delivery of this InsertOrderTemporally.  # noqa: E501
        :type: str
        """

        self._delivery = delivery

    @property
    def address(self):
        """Gets the address of this InsertOrderTemporally.  # noqa: E501


        :return: The address of this InsertOrderTemporally.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this InsertOrderTemporally.


        :param address: The address of this InsertOrderTemporally.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def phone(self):
        """Gets the phone of this InsertOrderTemporally.  # noqa: E501


        :return: The phone of this InsertOrderTemporally.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this InsertOrderTemporally.


        :param phone: The phone of this InsertOrderTemporally.  # noqa: E501
        :type: str
        """

        self._phone = phone

    @property
    def checking(self):
        """Gets the checking of this InsertOrderTemporally.  # noqa: E501


        :return: The checking of this InsertOrderTemporally.  # noqa: E501
        :rtype: bool
        """
        return self._checking

    @checking.setter
    def checking(self, checking):
        """Sets the checking of this InsertOrderTemporally.


        :param checking: The checking of this InsertOrderTemporally.  # noqa: E501
        :type: bool
        """
        if checking is None:
            raise ValueError("Invalid value for `checking`, must not be `None`")  # noqa: E501

        self._checking = checking

    @property
    def payment_receipt(self):
        """Gets the payment_receipt of this InsertOrderTemporally.  # noqa: E501


        :return: The payment_receipt of this InsertOrderTemporally.  # noqa: E501
        :rtype: str
        """
        return self._payment_receipt

    @payment_receipt.setter
    def payment_receipt(self, payment_receipt):
        """Sets the payment_receipt of this InsertOrderTemporally.


        :param payment_receipt: The payment_receipt of this InsertOrderTemporally.  # noqa: E501
        :type: str
        """

        self._payment_receipt = payment_receipt

    @property
    def comment(self):
        """Gets the comment of this InsertOrderTemporally.  # noqa: E501


        :return: The comment of this InsertOrderTemporally.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this InsertOrderTemporally.


        :param comment: The comment of this InsertOrderTemporally.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def info_delivery(self):
        """Gets the info_delivery of this InsertOrderTemporally.  # noqa: E501


        :return: The info_delivery of this InsertOrderTemporally.  # noqa: E501
        :rtype: str
        """
        return self._info_delivery

    @info_delivery.setter
    def info_delivery(self, info_delivery):
        """Sets the info_delivery of this InsertOrderTemporally.


        :param info_delivery: The info_delivery of this InsertOrderTemporally.  # noqa: E501
        :type: str
        """

        self._info_delivery = info_delivery

    @property
    def partner(self):
        """Gets the partner of this InsertOrderTemporally.  # noqa: E501


        :return: The partner of this InsertOrderTemporally.  # noqa: E501
        :rtype: bool
        """
        return self._partner

    @partner.setter
    def partner(self, partner):
        """Sets the partner of this InsertOrderTemporally.


        :param partner: The partner of this InsertOrderTemporally.  # noqa: E501
        :type: bool
        """

        self._partner = partner

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InsertOrderTemporally, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InsertOrderTemporally):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
