# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MessageTgBase(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'bot_token': 'str',
        'video_id': 'str',
        'text': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'bot_token': 'bot_token',
        'video_id': 'video_id',
        'text': 'text'
    }

    def __init__(self, id=None, name=None, bot_token=None, video_id=None, text=None):  # noqa: E501
        """MessageTgBase - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._bot_token = None
        self._video_id = None
        self._text = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if bot_token is not None:
            self.bot_token = bot_token
        if video_id is not None:
            self.video_id = video_id
        if text is not None:
            self.text = text

    @property
    def id(self):
        """Gets the id of this MessageTgBase.  # noqa: E501


        :return: The id of this MessageTgBase.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MessageTgBase.


        :param id: The id of this MessageTgBase.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this MessageTgBase.  # noqa: E501


        :return: The name of this MessageTgBase.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MessageTgBase.


        :param name: The name of this MessageTgBase.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def bot_token(self):
        """Gets the bot_token of this MessageTgBase.  # noqa: E501


        :return: The bot_token of this MessageTgBase.  # noqa: E501
        :rtype: str
        """
        return self._bot_token

    @bot_token.setter
    def bot_token(self, bot_token):
        """Sets the bot_token of this MessageTgBase.


        :param bot_token: The bot_token of this MessageTgBase.  # noqa: E501
        :type: str
        """

        self._bot_token = bot_token

    @property
    def video_id(self):
        """Gets the video_id of this MessageTgBase.  # noqa: E501


        :return: The video_id of this MessageTgBase.  # noqa: E501
        :rtype: str
        """
        return self._video_id

    @video_id.setter
    def video_id(self, video_id):
        """Sets the video_id of this MessageTgBase.


        :param video_id: The video_id of this MessageTgBase.  # noqa: E501
        :type: str
        """

        self._video_id = video_id

    @property
    def text(self):
        """Gets the text of this MessageTgBase.  # noqa: E501


        :return: The text of this MessageTgBase.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this MessageTgBase.


        :param text: The text of this MessageTgBase.  # noqa: E501
        :type: str
        """

        self._text = text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MessageTgBase, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MessageTgBase):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
