# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QuantityBaseDb(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'item_id': 'str',
        'stock_id': 'str',
        'size_id': 'int',
        'count': 'int',
        'centimeter_id': 'str',
        'stock': 'StockBase',
        'size': 'SizeBase',
        'centimeter': 'CentimeterBase'
    }

    attribute_map = {
        'id': 'id',
        'item_id': 'item_id',
        'stock_id': 'stock_id',
        'size_id': 'size_id',
        'count': 'count',
        'centimeter_id': 'centimeter_id',
        'stock': 'stock',
        'size': 'size',
        'centimeter': 'centimeter'
    }

    def __init__(self, id=None, item_id=None, stock_id=None, size_id=None, count=None, centimeter_id=None, stock=None, size=None, centimeter=None):  # noqa: E501
        """QuantityBaseDb - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._item_id = None
        self._stock_id = None
        self._size_id = None
        self._count = None
        self._centimeter_id = None
        self._stock = None
        self._size = None
        self._centimeter = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if item_id is not None:
            self.item_id = item_id
        if stock_id is not None:
            self.stock_id = stock_id
        if size_id is not None:
            self.size_id = size_id
        if count is not None:
            self.count = count
        if centimeter_id is not None:
            self.centimeter_id = centimeter_id
        if stock is not None:
            self.stock = stock
        if size is not None:
            self.size = size
        if centimeter is not None:
            self.centimeter = centimeter

    @property
    def id(self):
        """Gets the id of this QuantityBaseDb.  # noqa: E501


        :return: The id of this QuantityBaseDb.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this QuantityBaseDb.


        :param id: The id of this QuantityBaseDb.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def item_id(self):
        """Gets the item_id of this QuantityBaseDb.  # noqa: E501


        :return: The item_id of this QuantityBaseDb.  # noqa: E501
        :rtype: str
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id):
        """Sets the item_id of this QuantityBaseDb.


        :param item_id: The item_id of this QuantityBaseDb.  # noqa: E501
        :type: str
        """

        self._item_id = item_id

    @property
    def stock_id(self):
        """Gets the stock_id of this QuantityBaseDb.  # noqa: E501


        :return: The stock_id of this QuantityBaseDb.  # noqa: E501
        :rtype: str
        """
        return self._stock_id

    @stock_id.setter
    def stock_id(self, stock_id):
        """Sets the stock_id of this QuantityBaseDb.


        :param stock_id: The stock_id of this QuantityBaseDb.  # noqa: E501
        :type: str
        """

        self._stock_id = stock_id

    @property
    def size_id(self):
        """Gets the size_id of this QuantityBaseDb.  # noqa: E501


        :return: The size_id of this QuantityBaseDb.  # noqa: E501
        :rtype: int
        """
        return self._size_id

    @size_id.setter
    def size_id(self, size_id):
        """Sets the size_id of this QuantityBaseDb.


        :param size_id: The size_id of this QuantityBaseDb.  # noqa: E501
        :type: int
        """

        self._size_id = size_id

    @property
    def count(self):
        """Gets the count of this QuantityBaseDb.  # noqa: E501


        :return: The count of this QuantityBaseDb.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this QuantityBaseDb.


        :param count: The count of this QuantityBaseDb.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def centimeter_id(self):
        """Gets the centimeter_id of this QuantityBaseDb.  # noqa: E501


        :return: The centimeter_id of this QuantityBaseDb.  # noqa: E501
        :rtype: str
        """
        return self._centimeter_id

    @centimeter_id.setter
    def centimeter_id(self, centimeter_id):
        """Sets the centimeter_id of this QuantityBaseDb.


        :param centimeter_id: The centimeter_id of this QuantityBaseDb.  # noqa: E501
        :type: str
        """

        self._centimeter_id = centimeter_id

    @property
    def stock(self):
        """Gets the stock of this QuantityBaseDb.  # noqa: E501


        :return: The stock of this QuantityBaseDb.  # noqa: E501
        :rtype: StockBase
        """
        return self._stock

    @stock.setter
    def stock(self, stock):
        """Sets the stock of this QuantityBaseDb.


        :param stock: The stock of this QuantityBaseDb.  # noqa: E501
        :type: StockBase
        """

        self._stock = stock

    @property
    def size(self):
        """Gets the size of this QuantityBaseDb.  # noqa: E501


        :return: The size of this QuantityBaseDb.  # noqa: E501
        :rtype: SizeBase
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this QuantityBaseDb.


        :param size: The size of this QuantityBaseDb.  # noqa: E501
        :type: SizeBase
        """

        self._size = size

    @property
    def centimeter(self):
        """Gets the centimeter of this QuantityBaseDb.  # noqa: E501


        :return: The centimeter of this QuantityBaseDb.  # noqa: E501
        :rtype: CentimeterBase
        """
        return self._centimeter

    @centimeter.setter
    def centimeter(self, centimeter):
        """Sets the centimeter of this QuantityBaseDb.


        :param centimeter: The centimeter of this QuantityBaseDb.  # noqa: E501
        :type: CentimeterBase
        """

        self._centimeter = centimeter

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QuantityBaseDb, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QuantityBaseDb):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
