# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserBase(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'user_id': 'int',
        'first_name': 'str',
        'address': 'str',
        'phone': 'str',
        'last_mess': 'int',
        'items': 'str'
    }

    attribute_map = {
        'id': 'id',
        'user_id': 'user_id',
        'first_name': 'first_name',
        'address': 'address',
        'phone': 'phone',
        'last_mess': 'last_mess',
        'items': 'items'
    }

    def __init__(self, id=None, user_id=None, first_name=None, address=None, phone=None, last_mess=None, items=None):  # noqa: E501
        """UserBase - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._user_id = None
        self._first_name = None
        self._address = None
        self._phone = None
        self._last_mess = None
        self._items = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if user_id is not None:
            self.user_id = user_id
        if first_name is not None:
            self.first_name = first_name
        if address is not None:
            self.address = address
        if phone is not None:
            self.phone = phone
        if last_mess is not None:
            self.last_mess = last_mess
        if items is not None:
            self.items = items

    @property
    def id(self):
        """Gets the id of this UserBase.  # noqa: E501


        :return: The id of this UserBase.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserBase.


        :param id: The id of this UserBase.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def user_id(self):
        """Gets the user_id of this UserBase.  # noqa: E501


        :return: The user_id of this UserBase.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this UserBase.


        :param user_id: The user_id of this UserBase.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def first_name(self):
        """Gets the first_name of this UserBase.  # noqa: E501


        :return: The first_name of this UserBase.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this UserBase.


        :param first_name: The first_name of this UserBase.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def address(self):
        """Gets the address of this UserBase.  # noqa: E501


        :return: The address of this UserBase.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this UserBase.


        :param address: The address of this UserBase.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def phone(self):
        """Gets the phone of this UserBase.  # noqa: E501


        :return: The phone of this UserBase.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this UserBase.


        :param phone: The phone of this UserBase.  # noqa: E501
        :type: str
        """

        self._phone = phone

    @property
    def last_mess(self):
        """Gets the last_mess of this UserBase.  # noqa: E501


        :return: The last_mess of this UserBase.  # noqa: E501
        :rtype: int
        """
        return self._last_mess

    @last_mess.setter
    def last_mess(self, last_mess):
        """Sets the last_mess of this UserBase.


        :param last_mess: The last_mess of this UserBase.  # noqa: E501
        :type: int
        """

        self._last_mess = last_mess

    @property
    def items(self):
        """Gets the items of this UserBase.  # noqa: E501


        :return: The items of this UserBase.  # noqa: E501
        :rtype: str
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this UserBase.


        :param items: The items of this UserBase.  # noqa: E501
        :type: str
        """

        self._items = items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserBase, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserBase):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
