# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserBaseDb(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'user_id': 'int',
        'first_name': 'str',
        'username': 'str',
        'stock': 'StockBase',
        'users_bots': 'list[UserBotBase]'
    }

    attribute_map = {
        'id': 'id',
        'user_id': 'user_id',
        'first_name': 'first_name',
        'username': 'username',
        'stock': 'stock',
        'users_bots': 'users_bots'
    }

    def __init__(self, id=None, user_id=None, first_name=None, username=None, stock=None, users_bots=None):  # noqa: E501
        """UserBaseDb - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._user_id = None
        self._first_name = None
        self._username = None
        self._stock = None
        self._users_bots = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if user_id is not None:
            self.user_id = user_id
        if first_name is not None:
            self.first_name = first_name
        if username is not None:
            self.username = username
        if stock is not None:
            self.stock = stock
        if users_bots is not None:
            self.users_bots = users_bots

    @property
    def id(self):
        """Gets the id of this UserBaseDb.  # noqa: E501


        :return: The id of this UserBaseDb.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserBaseDb.


        :param id: The id of this UserBaseDb.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def user_id(self):
        """Gets the user_id of this UserBaseDb.  # noqa: E501


        :return: The user_id of this UserBaseDb.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this UserBaseDb.


        :param user_id: The user_id of this UserBaseDb.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def first_name(self):
        """Gets the first_name of this UserBaseDb.  # noqa: E501


        :return: The first_name of this UserBaseDb.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this UserBaseDb.


        :param first_name: The first_name of this UserBaseDb.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def username(self):
        """Gets the username of this UserBaseDb.  # noqa: E501


        :return: The username of this UserBaseDb.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UserBaseDb.


        :param username: The username of this UserBaseDb.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def stock(self):
        """Gets the stock of this UserBaseDb.  # noqa: E501


        :return: The stock of this UserBaseDb.  # noqa: E501
        :rtype: StockBase
        """
        return self._stock

    @stock.setter
    def stock(self, stock):
        """Sets the stock of this UserBaseDb.


        :param stock: The stock of this UserBaseDb.  # noqa: E501
        :type: StockBase
        """

        self._stock = stock

    @property
    def users_bots(self):
        """Gets the users_bots of this UserBaseDb.  # noqa: E501


        :return: The users_bots of this UserBaseDb.  # noqa: E501
        :rtype: list[UserBotBase]
        """
        return self._users_bots

    @users_bots.setter
    def users_bots(self, users_bots):
        """Sets the users_bots of this UserBaseDb.


        :param users_bots: The users_bots of this UserBaseDb.  # noqa: E501
        :type: list[UserBotBase]
        """

        self._users_bots = users_bots

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserBaseDb, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserBaseDb):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
