# coding: utf-8

"""
    Rest DB

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class YookassaPaymentInsert(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'purchase_id': 'int',
        'payment_id': 'str',
        'status': 'str',
        'email': 'str'
    }

    attribute_map = {
        'purchase_id': 'purchase_id',
        'payment_id': 'payment_id',
        'status': 'status',
        'email': 'email'
    }

    def __init__(self, purchase_id=None, payment_id=None, status=None, email=None):  # noqa: E501
        """YookassaPaymentInsert - a model defined in Swagger"""  # noqa: E501
        self._purchase_id = None
        self._payment_id = None
        self._status = None
        self._email = None
        self.discriminator = None
        self.purchase_id = purchase_id
        self.payment_id = payment_id
        self.status = status
        self.email = email

    @property
    def purchase_id(self):
        """Gets the purchase_id of this YookassaPaymentInsert.  # noqa: E501


        :return: The purchase_id of this YookassaPaymentInsert.  # noqa: E501
        :rtype: int
        """
        return self._purchase_id

    @purchase_id.setter
    def purchase_id(self, purchase_id):
        """Sets the purchase_id of this YookassaPaymentInsert.


        :param purchase_id: The purchase_id of this YookassaPaymentInsert.  # noqa: E501
        :type: int
        """
        if purchase_id is None:
            raise ValueError("Invalid value for `purchase_id`, must not be `None`")  # noqa: E501

        self._purchase_id = purchase_id

    @property
    def payment_id(self):
        """Gets the payment_id of this YookassaPaymentInsert.  # noqa: E501


        :return: The payment_id of this YookassaPaymentInsert.  # noqa: E501
        :rtype: str
        """
        return self._payment_id

    @payment_id.setter
    def payment_id(self, payment_id):
        """Sets the payment_id of this YookassaPaymentInsert.


        :param payment_id: The payment_id of this YookassaPaymentInsert.  # noqa: E501
        :type: str
        """
        if payment_id is None:
            raise ValueError("Invalid value for `payment_id`, must not be `None`")  # noqa: E501

        self._payment_id = payment_id

    @property
    def status(self):
        """Gets the status of this YookassaPaymentInsert.  # noqa: E501


        :return: The status of this YookassaPaymentInsert.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this YookassaPaymentInsert.


        :param status: The status of this YookassaPaymentInsert.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def email(self):
        """Gets the email of this YookassaPaymentInsert.  # noqa: E501


        :return: The email of this YookassaPaymentInsert.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this YookassaPaymentInsert.


        :param email: The email of this YookassaPaymentInsert.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(YookassaPaymentInsert, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, YookassaPaymentInsert):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
